[versions]
workspace_version = "4.4.0.1"
jetbrains_annotation_version = "26.0.2"

[libraries]
jetbrains_annotation = {module = "org.jetbrains:annotations", version.ref = "jetbrains_annotation_version" }

[plugins]
workspace = { id = "com.wildermods.workspace", version.ref = "workspace_version" }